server:
  port: 8011

spring:
  application:
    name: role-server
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clouddb?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  redis:
    host: 192.168.56.10
    port: 6379
    # 数据库
    database: 0
    # 连接超时
    timeout: 10000ms
    lettuce:
      pool:
        # 最大连接数，默认8
        max-active: 8
        # 最大连接阻塞等待时间，默认-1
        max-wait: 10000ms
        # 最大空闲连接，默认8
        max-idle: 8
        # 最小空闲连接，默认0
        min-idle: 5
    password: 111111
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
management:
  endpoints:
    web:
      exposure:
        include: '*'